---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Sprint-boot app
  labels:
    app: web






spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      pods:
        - name: database
          image: nginx
          ports:
            - containerPort: 80
        - name: rss-reader
          image: nickchase/rss-php-nginx:v1
          ports:
            - containerPort: 88














